{
	"version": 1634602380,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/minga-sheet0.png",
		"images/lemon-sheet0.png",
		"images/lemon-sheet1.png",
		"images/lemon-sheet2.png",
		"images/tilemap.png",
		"images/tiledbackground.png",
		"images/score.png",
		"images/door-sheet0.png",
		"images/door-sheet1.png",
		"images/logo-sheet0.png",
		"images/enemyshoot-sheet0.png",
		"images/bullet-sheet0.png",
		"images/spawn-sheet0.png",
		"images/sprite-sheet0.png",
		"media/robot thud.m4a",
		"media/robot thud.ogg",
		"media/toss.m4a",
		"media/toss.ogg",
		"media/winyay.m4a",
		"media/winyay.ogg",
		"media/wanomenuloop.m4a",
		"media/wanomenuloop.ogg",
		"media/mingamusicloop.m4a",
		"media/mingamusicloop.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}